### PR TITLE
Ensure we have correct padding everywhere

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Comment by sebsto** [comment]
I just tested xcodeinstall against this branch, end-to-end, and it works for me.
Both the padding and the `calculateSharedSecret` with binary password allows to authenticate on Apple's SRP.

Thank you Adam

**Comment by adam-fowler** [comment]
@sebsto There are some more changes in this PR. Can you verify again.
You might need to change a couple of parameter names

**Comment by sebsto** [comment]
@adam-fowler thank you for the heads up I just test this branch with latest commit (https://github.com/adam-fowler/swift-srp/commit/9468111ec05b2beceecb4726fdd5006907173319) and it still works for me.

**Comment by abiligiri** [comment]
@adam-fowler thanks for these changes. Can you keep the public constructor for keypair? It will enable unit tests like these https://github.com/XcodesOrg/XcodesApp/blob/main/XcodesTests/AppStateUpdateTests.swift#L274 (specifically https://github.com/XcodesOrg/XcodesApp/blob/main/XcodesTests/AppStateUpdateTests.swift#L296)

**Comment by adam-fowler** [comment]
> @adam-fowler thanks for these changes. Can you keep the public constructor for keypair? It will enable unit tests like these https://github.com/XcodesOrg/XcodesApp/blob/main/XcodesTests/AppStateUpdateTests.swift#L274 (specifically https://github.com/XcodesOrg/XcodesApp/blob/main/XcodesTests/AppStateUpdateTests.swift#L296)

The API has been re-designed to ensure we don't get bad values. If you still feel the need to re-test the library I guess I could use an `@_spi(Testing)` to make the symbol available for testing.

**Pull request merged**
